[server]
port = 8080
log_level = "info,pivot_server=debug,chromiumoxide=error"

[database]
path = "database.sqlite"

[chrome]
binary = "/usr/bin/google-chrome"
user_data_dir = "/home/pbs/Workspace/ChromeData"
launch_if_needed = true

#[scorer]
#type = "deepseek"
#api_key = "sk-fbbc41dbf3a545969efa765524e1ef89"
#model = "deepseek-reasoner"
